"""create new indexes

Revision ID: 0a113a8bc0df
Revises: 6d2a03b326f9
Create Date: 2025-06-13 10:28:06.674777

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0a113a8bc0df"
down_revision = "6d2a03b326f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("access_request", schema=None) as batch_op:
        batch_op.create_index("idx_access_request_approved_membership_id", ["approved_membership_id"], unique=False)
        batch_op.create_index("idx_access_request_requested_group_id", ["requested_group_id"], unique=False)
        batch_op.create_index("idx_access_request_requester_user_id", ["requester_user_id"], unique=False)
        batch_op.create_index("idx_access_request_resolver_user_id", ["resolver_user_id"], unique=False)
        batch_op.create_index("idx_access_request_status_resolved", ["status", "resolved_at"], unique=False)

    with op.batch_alter_table("app_group", schema=None) as batch_op:
        batch_op.create_index("idx_app_group_app_id", ["app_id"], unique=False)

    with op.batch_alter_table("okta_user", schema=None) as batch_op:
        batch_op.create_index("idx_okta_user_manager_id", ["manager_id"], unique=False)

    with op.batch_alter_table("okta_user_group_member", schema=None) as batch_op:
        batch_op.create_index("idx_okta_user_group_member_created_actor_id", ["created_actor_id"], unique=False)
        batch_op.create_index("idx_okta_user_group_member_ended_actor_id", ["ended_actor_id"], unique=False)
        batch_op.create_index("idx_okta_user_group_member_group_ended", ["group_id", "ended_at"], unique=False)
        batch_op.create_index("idx_okta_user_group_member_group_id", ["group_id"], unique=False)
        batch_op.create_index("idx_okta_user_group_member_role_group_map_id", ["role_group_map_id"], unique=False)
        batch_op.create_index("idx_okta_user_group_member_user_group", ["user_id", "group_id"], unique=False)
        batch_op.create_index("idx_okta_user_group_member_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("role_group_map", schema=None) as batch_op:
        batch_op.create_index("idx_role_group_map_created_actor_id", ["created_actor_id"], unique=False)
        batch_op.create_index("idx_role_group_map_ended_actor_id", ["ended_actor_id"], unique=False)
        batch_op.create_index("idx_role_group_map_group_id", ["group_id"], unique=False)
        batch_op.create_index("idx_role_group_map_role_id", ["role_id"], unique=False)

    with op.batch_alter_table("role_request", schema=None) as batch_op:
        batch_op.create_index("idx_role_request_approved_membership_id", ["approved_membership_id"], unique=False)
        batch_op.create_index("idx_role_request_requested_group_id", ["requested_group_id"], unique=False)
        batch_op.create_index("idx_role_request_requester_role_id", ["requester_role_id"], unique=False)
        batch_op.create_index("idx_role_request_requester_user_id", ["requester_user_id"], unique=False)
        batch_op.create_index("idx_role_request_resolver_user_id", ["resolver_user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_request", schema=None) as batch_op:
        batch_op.drop_index("idx_role_request_resolver_user_id")
        batch_op.drop_index("idx_role_request_requester_user_id")
        batch_op.drop_index("idx_role_request_requester_role_id")
        batch_op.drop_index("idx_role_request_requested_group_id")
        batch_op.drop_index("idx_role_request_approved_membership_id")

    with op.batch_alter_table("role_group_map", schema=None) as batch_op:
        batch_op.drop_index("idx_role_group_map_role_id")
        batch_op.drop_index("idx_role_group_map_group_id")
        batch_op.drop_index("idx_role_group_map_ended_actor_id")
        batch_op.drop_index("idx_role_group_map_created_actor_id")

    with op.batch_alter_table("okta_user_group_member", schema=None) as batch_op:
        batch_op.drop_index("idx_okta_user_group_member_user_id")
        batch_op.drop_index("idx_okta_user_group_member_user_group")
        batch_op.drop_index("idx_okta_user_group_member_role_group_map_id")
        batch_op.drop_index("idx_okta_user_group_member_group_id")
        batch_op.drop_index("idx_okta_user_group_member_group_ended")
        batch_op.drop_index("idx_okta_user_group_member_ended_actor_id")
        batch_op.drop_index("idx_okta_user_group_member_created_actor_id")

    with op.batch_alter_table("okta_user", schema=None) as batch_op:
        batch_op.drop_index("idx_okta_user_manager_id")

    with op.batch_alter_table("app_group", schema=None) as batch_op:
        batch_op.drop_index("idx_app_group_app_id")

    with op.batch_alter_table("access_request", schema=None) as batch_op:
        batch_op.drop_index("idx_access_request_status_resolved")
        batch_op.drop_index("idx_access_request_resolver_user_id")
        batch_op.drop_index("idx_access_request_requester_user_id")
        batch_op.drop_index("idx_access_request_requested_group_id")
        batch_op.drop_index("idx_access_request_approved_membership_id")

    # ### end Alembic commands ###
