"""do not renew

Revision ID: 0a7f1ca77b12
Revises: 6d2a03b326f9
Create Date: 2025-06-08 18:18:38.868290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7f1ca77b12'
down_revision = '6d2a03b326f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('okta_user_group_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('should_expire', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('role_group_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('should_expire', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_group_map', schema=None) as batch_op:
        batch_op.drop_column('should_expire')

    with op.batch_alter_table('okta_user_group_member', schema=None) as batch_op:
        batch_op.drop_column('should_expire')

    # ### end Alembic commands ###
