"""add app_group_lifecycle_plugin to app

Revision ID: 0ed12d651875
Revises: cbc5bb2f05b7
Create Date: 2025-10-24 21:03:01.388376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed12d651875'
down_revision = 'cbc5bb2f05b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_group_lifecycle_plugin', sa.Unicode(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('app_group_lifecycle_plugin')

    # ### end Alembic commands ###
