"""Group requests

Revision ID: 11a0117dabea
Revises: 0ed12d651875
Create Date: 2026-03-03 22:13:36.425663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11a0117dabea'
down_revision = '0ed12d651875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_request',
    sa.Column('id', sa.Unicode(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='accessrequeststatus'), nullable=False),
    sa.Column('requester_user_id', sa.Unicode(length=50), nullable=False),
    sa.Column('requested_group_name', sa.Unicode(length=255), nullable=False),
    sa.Column('requested_group_description', sa.Unicode(length=1024), nullable=False),
    sa.Column('requested_group_type', sa.Unicode(length=50), nullable=False),
    sa.Column('requested_app_id', sa.Unicode(length=20), nullable=True),
    sa.Column('requested_ownership_ending_at', sa.DateTime(), nullable=True),
    sa.Column('requested_group_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), server_default="{}", nullable=False),
    sa.Column('request_reason', sa.Unicode(length=1024), nullable=False),
    sa.Column('resolver_user_id', sa.Unicode(length=50), nullable=True),
    sa.Column('resolved_group_name', sa.Unicode(length=255), nullable=False),
    sa.Column('resolved_group_description', sa.Unicode(length=1024), nullable=False),
    sa.Column('resolved_group_type', sa.Unicode(length=50), nullable=False),
    sa.Column('resolved_app_id', sa.Unicode(length=20), nullable=True),
    sa.Column('resolved_ownership_ending_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_group_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), server_default="{}", nullable=False),
    sa.Column('resolution_reason', sa.Unicode(length=1024), nullable=False),
    sa.Column('approved_group_id', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['approved_group_id'], ['okta_group.id'], name=op.f('fk_group_request_approved_group_id_okta_group')),
    sa.ForeignKeyConstraint(['requested_app_id'], ['app.id'], name=op.f('fk_group_request_requested_app_id_app')),
    sa.ForeignKeyConstraint(['requester_user_id'], ['okta_user.id'], name=op.f('fk_group_request_requester_user_id_okta_user')),
    sa.ForeignKeyConstraint(['resolved_app_id'], ['app.id'], name=op.f('fk_group_request_resolved_app_id_app')),
    sa.ForeignKeyConstraint(['resolver_user_id'], ['okta_user.id'], name=op.f('fk_group_request_resolver_user_id_okta_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_request')
    # ### end Alembic commands ###
