"""do not renew

Revision ID: cbc5bb2f05b7
Revises: 6d2a03b326f9
Create Date: 2025-06-27 13:55:16.355027

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = "cbc5bb2f05b7"
down_revision = "6d2a03b326f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("okta_user_group_member", schema=None) as batch_op:
        batch_op.add_column(sa.Column("should_expire", sa.Boolean(), server_default=expression.false(), nullable=False))

    with op.batch_alter_table("role_group_map", schema=None) as batch_op:
        batch_op.add_column(sa.Column("should_expire", sa.Boolean(), server_default=expression.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_group_map", schema=None) as batch_op:
        batch_op.drop_column("should_expire")

    with op.batch_alter_table("okta_user_group_member", schema=None) as batch_op:
        batch_op.drop_column("should_expire")

    # ### end Alembic commands ###
