/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import type * as Schemas from './apiSchemas';

export type Tag = Schemas.Tag;

export type App = Schemas.App;

export type PolymorphicGroup = Schemas.OktaGroup | Schemas.AppGroup | Schemas.RoleGroup;
