/**
 * Generated by @openapi-codegen
 *
 * @version Not Defined
 */
/**
 * Response for `GET /api/requests/{id}` only.
 *
 * Flask `AccessRequestResource.get()` `only=` retains a richer
 * `requested_group` projection (group tags + role-association mappings on
 * role groups, plus `app`/`is_owner` on app groups). We split the detail
 * shape from the list/POST/PUT shape (`AccessRequestSummary`) because
 * SQLAlchemy `lazy="raise_on_sql"` won't let one Pydantic model
 * conditionally include the relationships at runtime — the eager-loads
 * differ per endpoint.
 */
export type AccessRequestDetail = {
  id: string;
  requester_user_id?: string | null;
  requested_group_id?: string | null;
  /**
   * @default false
   */
  request_ownership?: boolean;
  /**
   * @default
   */
  request_reason?: string | null;
  request_ending_at?: string | null;
  status: string;
  resolver_user_id?: string | null;
  /**
   * @default
   */
  resolution_reason?: string | null;
  resolved_at?: string | null;
  approval_ending_at?: string | null;
  created_at: string | null;
  updated_at: string | null;
  requester?: OktaUserSummary | null;
  active_requester?: OktaUserSummary | null;
  requested_group?:
    | (
        | (Omit<AccessRequestOktaGroupRef, 'type'> & {
            type: 'okta_group';
          })
        | (Omit<AccessRequestRoleGroupRef, 'type'> & {
            type: 'role_group';
          })
        | (Omit<AccessRequestAppGroupRef, 'type'> & {
            type: 'app_group';
          })
      )
    | null;
  active_requested_group?: GroupRef | null;
  resolver?: OktaUserSummary | null;
  active_resolver?: OktaUserSummary | null;
};

/**
 * Response for `GET /api/requests`, `POST /api/requests`, and
 * `PUT /api/requests/{id}`. Matches Flask's per-endpoint `only=` lists
 * via null-emission: scalar fields the frontend reads (resolution_reason,
 * request_reason, etc.) are emitted as `null` when absent. The
 * `requested_group` is the lightweight `GroupRef` — no group tags or
 * role-association mappings, which only the detail page renders.
 */
export type AccessRequestSummary = {
  id: string;
  requester_user_id?: string | null;
  requested_group_id?: string | null;
  /**
   * @default false
   */
  request_ownership?: boolean;
  /**
   * @default
   */
  request_reason?: string | null;
  request_ending_at?: string | null;
  status: string;
  resolver_user_id?: string | null;
  /**
   * @default
   */
  resolution_reason?: string | null;
  resolved_at?: string | null;
  approval_ending_at?: string | null;
  created_at: string | null;
  updated_at: string | null;
  requester?: OktaUserSummary | null;
  active_requester?: OktaUserSummary | null;
  requested_group?: GroupRef | null;
  active_requested_group?: GroupRef | null;
  resolver?: OktaUserSummary | null;
  active_resolver?: OktaUserSummary | null;
};

/**
 * Full App detail.
 */
export type AppDetail = {
  id: string;
  name: string;
  description?: string | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
  app_group_lifecycle_plugin?: string | null;
  plugin_data?: {
    [key: string]: any;
  } | null;
  active_app_tags?: AppTagMapDetail[];
  active_owner_app_groups?: AppGroupForAppDetail[];
  active_non_owner_app_groups?: AppGroupForAppDetail[];
};

export type AppGroupDetail = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  externally_managed_data?: {
    [key: string]: any;
  } | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
  active_user_memberships?: OktaUserGroupMemberDetail[];
  active_user_ownerships?: OktaUserGroupMemberDetail[];
  active_group_tags?: OktaGroupTagMapDetail[];
  /**
   * @default app_group
   */
  type?: string;
  app_id?: string | null;
  /**
   * @default false
   */
  is_owner?: boolean;
  plugin_data?: {
    [key: string]: any;
  } | null;
  app?: AppIdRef | null;
  active_role_member_mappings?: RoleGroupMapDetail[];
  active_role_owner_mappings?: RoleGroupMapDetail[];
};

/**
 * Slimmer shape used inside `AppDetail.active_*_app_groups`.
 *
 * Flask's `AppResource.get()` excluded `active_role_member_mappings`,
 * `active_role_owner_mappings`, and `active_group_tags` on the nested
 * app-groups via dotted-path entries in `DEFAULT_SCHEMA_DISPLAY_EXCLUSIONS`.
 * The outer `AppGroupDetail` retains them for direct
 * `GET /api/groups/{id}` calls; this variant drops them when the same
 * rows are embedded inside an `AppDetail` payload.
 */
export type AppGroupForAppDetail = {
  id: string;
  /**
   * @default app_group
   */
  type?: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  externally_managed_data?: {
    [key: string]: any;
  } | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
  app_id?: string | null;
  /**
   * @default false
   */
  is_owner?: boolean;
  plugin_data?: {
    [key: string]: any;
  } | null;
  app?: AppIdRef | null;
  active_user_memberships?: OktaUserGroupMemberDetail[];
  active_user_ownerships?: OktaUserGroupMemberDetail[];
};

/**
 * Wire shape for `GET /api/plugins/app-group-lifecycle/{id}/app-config-props`.
 */
export type AppGroupLifecyclePluginAppConfig = {
  [key: string]: PluginConfigProp;
};

/**
 * Wire shape for `GET /api/plugins/app-group-lifecycle/{id}/app-status-props`.
 */
export type AppGroupLifecyclePluginAppStatus = {
  [key: string]: PluginStatusProp;
};

/**
 * Wire shape for `GET /api/plugins/app-group-lifecycle/{id}/group-config-props`.
 */
export type AppGroupLifecyclePluginGroupConfig = {
  [key: string]: PluginConfigProp;
};

/**
 * Wire shape for `GET /api/plugins/app-group-lifecycle/{id}/group-status-props`.
 */
export type AppGroupLifecyclePluginGroupStatus = {
  [key: string]: PluginStatusProp;
};

/**
 * Wire shape for `GET /api/plugins/app-group-lifecycle`.
 */
export type AppGroupLifecyclePlugins = PluginInfo[];

export type AppGroupRef = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  deleted_at?: string | null;
  /**
   * @default app_group
   */
  type?: string;
  app_id?: string | null;
  /**
   * @default false
   */
  is_owner?: boolean;
  app?: AppIdRef | null;
};

export type AppGroupSummary = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  created_at: string | null;
  updated_at: string | null;
  active_group_tags?: OktaGroupTagMapDetail[];
  /**
   * @default app_group
   */
  type?: string;
  app?: AppIdRef | null;
};

/**
 * Inline reference to an App by id (used in compact group views).
 *
 * Flask `AppGroupSchema.app = Nested(AppSchema, only=("id", "name",
 * "deleted_at", "app_group_lifecycle_plugin"))` exposed the lifecycle
 * plugin id on every embedded app reference so the React frontend can
 * dispatch on plugin behaviour without a follow-up `/api/apps/{id}` fetch.
 */
export type AppIdRef = {
  id: string;
  name?: string | null;
  deleted_at?: string | null;
  app_group_lifecycle_plugin?: string | null;
};

export type AppSummary = {
  id: string;
  name: string;
  description?: string | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
};

export type AppTagMapDetail = {
  created_at: string | null;
  ended_at?: string | null;
  active_tag?: TagSummary | null;
  active_app?: AppSummary | null;
};

/**
 * Mirrors `_serialize_role_group_map` (audit.py:229-245).
 */
export type AuditGroupRoleRow = {
  id: number;
  role_group_id: string;
  group_id: string;
  is_owner: boolean;
  should_expire?: boolean | null;
  /**
   * @default
   */
  created_reason?: string;
  created_at?: string | null;
  ended_at?: string | null;
  group?: GroupRefForAudit | null;
  role_group?: RoleGroupRefForAudit | null;
  created_actor?: UserSummaryForAudit | null;
  ended_actor?: UserSummaryForAudit | null;
};

export type AuditOrderBy = 'moniker' | 'created_at' | 'ended_at';

/**
 * Mirrors `_serialize_user_group_member` (audit.py:190-226).
 */
export type AuditUserGroupRow = {
  id: number;
  user_id: string;
  group_id: string;
  role_group_map_id?: number | null;
  is_owner: boolean;
  should_expire?: boolean | null;
  /**
   * @default
   */
  created_reason?: string;
  created_at?: string | null;
  updated_at?: string | null;
  ended_at?: string | null;
  user?: UserSummaryForAudit | null;
  group?: GroupRefForAudit | null;
  role_group_mapping?: RoleGroupMappingForAudit | null;
  access_request?: AccessRequestRef | null;
  created_actor?: UserSummaryForAudit | null;
  ended_actor?: UserSummaryForAudit | null;
};

export type CreateAccessRequestBody = {
  group_id: string;
  /**
   * @default false
   */
  group_owner?: boolean;
  /**
   * @default
   */
  reason?: string | null;
  ending_at?: string | null;
};

/**
 * Body for POST /api/apps.
 */
export type CreateAppBody = {
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  description?: string | null;
  initial_owner_id?: string | null;
  initial_owner_role_ids?: string[] | null;
  initial_additional_app_groups?: InitialAppGroupBody[] | null;
  tags_to_add?: string[] | null;
  app_group_lifecycle_plugin?: string | null;
  plugin_data?: {
    [key: string]: any;
  } | null;
};

export type CreateRoleRequestBody = {
  role_id: string;
  group_id: string;
  /**
   * @default false
   */
  group_owner?: boolean;
  /**
   * @default
   */
  reason?: string | null;
  ending_at?: string | null;
};

/**
 * Body for POST /api/tags.
 */
export type CreateTagBody = {
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  description?: string | null;
  constraints?: {
    [key: string]: any;
  } | null;
  /**
   * @default true
   */
  enabled?: boolean;
};

export type DeleteMessage = {
  deleted: boolean;
};

export type GroupDetail =
  | (Omit<OktaGroupDetail, 'type'> & {
      type: 'okta_group';
    })
  | (Omit<RoleGroupDetail, 'type'> & {
      type: 'role_group';
    })
  | (Omit<AppGroupDetail, 'type'> & {
      type: 'app_group';
    });

/**
 * Used by GET/PUT /api/groups/{id}/members.
 *
 * `members_should_expire` and `owners_should_expire` are lists of
 * OktaUserGroupMember row ids (integers). The other lists are user ids
 * (strings).
 */
export type GroupMember = {
  members?: string[];
  owners?: string[];
  members_to_add: string[];
  members_to_remove: string[];
  owners_to_add: string[];
  owners_to_remove: string[];
  members_should_expire?: number[];
  owners_should_expire?: number[];
  users_added_ending_at?: string | null;
  /**
   * @default
   */
  created_reason?: string | null;
};

/**
 * Wire shape for `GET/PUT /api/groups/{id}/members`.
 */
export type GroupMembersSummary = {
  members: string[];
  owners: string[];
};

export type GroupRef =
  | (Omit<OktaGroupRef, 'type'> & {
      type: 'okta_group';
    })
  | (Omit<RoleGroupRef, 'type'> & {
      type: 'role_group';
    })
  | (Omit<AppGroupRef, 'type'> & {
      type: 'app_group';
    });

export type GroupRequestDetail = {
  id: string;
  status: string;
  requested_group_name?: string | null;
  /**
   * @default
   */
  requested_group_description?: string | null;
  requested_group_type?: string | null;
  requested_app_id?: string | null;
  requested_group_tags?: string[];
  requested_ownership_ending_at?: string | null;
  /**
   * @default
   */
  request_reason?: string | null;
  /**
   * @default
   */
  resolved_group_name?: string | null;
  /**
   * @default
   */
  resolved_group_description?: string | null;
  /**
   * @default
   */
  resolved_group_type?: string | null;
  resolved_app_id?: string | null;
  resolved_group_tags?: string[];
  resolved_ownership_ending_at?: string | null;
  /**
   * @default
   */
  resolution_reason?: string | null;
  resolved_at?: string | null;
  approved_group_id?: string | null;
  created_at: string | null;
  updated_at: string | null;
  requester?: OktaUserSummary | null;
  resolver?: OktaUserSummary | null;
};

export type GroupSummary =
  | (Omit<OktaGroupSummary, 'type'> & {
      type: 'okta_group';
    })
  | (Omit<RoleGroupSummary, 'type'> & {
      type: 'role_group';
    })
  | (Omit<AppGroupSummary, 'type'> & {
      type: 'app_group';
    });

export type OktaGroupDetail = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  externally_managed_data?: {
    [key: string]: any;
  } | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
  active_user_memberships?: OktaUserGroupMemberDetail[];
  active_user_ownerships?: OktaUserGroupMemberDetail[];
  active_group_tags?: OktaGroupTagMapDetail[];
  /**
   * @default okta_group
   */
  type?: string;
  active_role_member_mappings?: RoleGroupMapDetail[];
  active_role_owner_mappings?: RoleGroupMapDetail[];
};

export type OktaGroupRef = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  deleted_at?: string | null;
  /**
   * @default okta_group
   */
  type?: string;
};

export type OktaGroupSummary = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  created_at: string | null;
  updated_at: string | null;
  active_group_tags?: OktaGroupTagMapDetail[];
  /**
   * @default okta_group
   */
  type?: string;
};

export type OktaGroupTagMapDetail = {
  created_at: string | null;
  ended_at?: string | null;
  active_tag?: TagSummary | null;
  active_group?: GroupRefForMembership | null;
  active_app_tag_mapping?: AppTagMapDetail | null;
};

export type OktaUserDetail = {
  id: string;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  display_name?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
  profile?: {
    [key: string]: any;
  };
  manager?: OktaUserManagerRef | null;
  active_group_memberships?: OktaUserGroupMemberDetail[];
  active_group_ownerships?: OktaUserGroupMemberDetail[];
};

export type OktaUserGroupMemberDetail = {
  id: number;
  is_owner?: boolean | null;
  created_at: string | null;
  updated_at?: string | null;
  ended_at?: string | null;
  /**
   * @default
   */
  created_reason?: string | null;
  should_expire?: boolean | null;
  created_actor?: OktaUserSummary | null;
  ended_actor?: OktaUserSummary | null;
  user?: OktaUserSummary | null;
  active_user?: OktaUserSummary | null;
  group?: GroupRefForMembership | null;
  active_group?: GroupRefForMembership | null;
  role_group_mapping?: RoleGroupMappingForMembership | null;
  active_role_group_mapping?: RoleGroupMappingForMembership | null;
};

/**
 * Embedded manager reference inside `OktaUserDetail`.
 *
 * Flask's `OktaUserSchema.manager = Nested(OktaUserSchema, exclude=(...))`
 * retained `profile` (filtered to `USER_DISPLAY_CUSTOM_ATTRIBUTES`). The
 * React user-detail page reads `manager.profile.Title` to render the
 * manager's job title alongside their name.
 */
export type OktaUserManagerRef = {
  id: string;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  display_name?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
  profile?: {
    [key: string]: any;
  };
};

export type OktaUserSummary = {
  id: string;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  display_name?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
};

export type PageTypeVarCustomizedAccessRequestSummary = {
  items: AccessRequestSummary[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedAppSummary = {
  items: AppSummary[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedAuditGroupRoleRow = {
  items: AuditGroupRoleRow[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedAuditUserGroupRow = {
  items: AuditUserGroupRow[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedGroupRequestDetail = {
  items: GroupRequestDetail[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedGroupSummary = {
  items: GroupSummary[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedOktaUserSummary = {
  items: OktaUserSummary[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedRoleGroupListItem = {
  items: RoleGroupListItem[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedRoleRequestSummary = {
  items: RoleRequestSummary[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

export type PageTypeVarCustomizedTagListItem = {
  items: TagListItem[];
  /**
   * @minimum 0
   */
  total: number;
  /**
   * @minimum 1
   */
  page: number;
  /**
   * @minimum 1
   */
  size: number;
  /**
   * @minimum 0
   */
  pages: number;
};

/**
 * Mirrors `AppGroupLifecyclePluginConfigProperty`.
 */
export type PluginConfigProp = {
  display_name: string;
  help_text?: string | null;
  /**
   * @default text
   */
  type?: 'text' | 'number' | 'boolean';
  default_value?: void;
  /**
   * @default false
   */
  required?: boolean;
  validation?: {
    [key: string]: any;
  } | null;
};

/**
 * Mirrors `AppGroupLifecyclePluginMetadata`.
 */
export type PluginInfo = {
  id: string;
  display_name: string;
  description: string;
};

/**
 * Mirrors `AppGroupLifecyclePluginStatusProperty`.
 */
export type PluginStatusProp = {
  display_name: string;
  help_text?: string | null;
  /**
   * @default text
   */
  type?: 'text' | 'number' | 'date' | 'boolean';
};

/**
 * RFC 9457 problem-detail envelope emitted for every HTTP error by
 * `api/exception_handlers.py` (Content-Type `application/problem+json`).
 *
 * Declared here so routers can advertise it via `responses={...}`; the
 * generated TypeScript client then types its `*Error` payloads against this
 * shape. Mirrors the hand-written `ErrorMessage` type in
 * `src/api/apiFetcher.ts`. All fields are optional on the wire (`type`
 * carries the RFC default, the rest are populated per error).
 */
export type ProblemDetail = {
  /**
   * @default about:blank
   */
  type?: string;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  errors?: ProblemDetailError[] | null;
};

/**
 * One entry in the non-standard `errors` extension that validation
 * problems carry (see `_validation_errors` in `api/exception_handlers.py`).
 */
export type ProblemDetailError = {
  type?: string | null;
  loc?: (string | number)[] | null;
  msg?: string | null;
  ctx?: {
    [key: string]: any;
  } | null;
};

export type ResolveAccessRequestBody = {
  approved: boolean;
  /**
   * @default
   */
  reason?: string | null;
  ending_at?: string | null;
};

export type ResolveGroupRequestBody = {
  approved: boolean;
  /**
   * @default
   */
  reason?: string | null;
  resolved_group_name?: string | null;
  resolved_group_description?: string | null;
  resolved_group_type?: string | null;
  resolved_app_id?: string | null;
  resolved_group_tags?: string[] | null;
  resolved_ownership_ending_at?: string | null;
};

export type ResolveRoleRequestBody = {
  approved: boolean;
  /**
   * @default
   */
  reason?: string | null;
  ending_at?: string | null;
};

export type RoleGroupDetail = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  externally_managed_data?: {
    [key: string]: any;
  } | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
  active_user_memberships?: OktaUserGroupMemberDetail[];
  active_user_ownerships?: OktaUserGroupMemberDetail[];
  active_group_tags?: OktaGroupTagMapDetail[];
  /**
   * @default role_group
   */
  type?: string;
  active_role_associated_group_member_mappings?: RoleGroupMapDetail[];
  active_role_associated_group_owner_mappings?: RoleGroupMapDetail[];
};

/**
 * Slim row shape for `GET /api/roles`.
 *
 * Flask `RoleList.get()` `only=(id, type, name, description, created_at,
 * updated_at)`. The role-list page does not render tags or role
 * associations, so we pay neither the loader cost nor the JSON bloat
 * from emitting them on every row.
 */
export type RoleGroupListItem = {
  id: string;
  /**
   * @default role_group
   */
  type?: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  created_at: string | null;
  updated_at: string | null;
};

export type RoleGroupMapDetail = {
  id: number;
  is_owner?: boolean | null;
  created_at: string | null;
  ended_at?: string | null;
  /**
   * @default
   */
  created_reason?: string | null;
  should_expire?: boolean | null;
  created_actor?: OktaUserSummary | null;
  ended_actor?: OktaUserSummary | null;
  role_group?: RoleGroupMembershipRef | null;
  active_role_group?: RoleGroupMembershipRef | null;
  group?: GroupRefForMembership | null;
  active_group?: GroupRefForMembership | null;
};

export type RoleGroupRef = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  deleted_at?: string | null;
  /**
   * @default role_group
   */
  type?: string;
};

export type RoleGroupSummary = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  created_at: string | null;
  updated_at: string | null;
  active_group_tags?: OktaGroupTagMapDetail[];
  /**
   * @default role_group
   */
  type?: string;
  active_role_associated_group_member_mappings?: RoleGroupMapDetail[];
  active_role_associated_group_owner_mappings?: RoleGroupMapDetail[];
};

/**
 * Used by GET/PUT /api/roles/{id}/members (role-to-group mappings).
 *
 * `groups_should_expire` and `owner_groups_should_expire` are RoleGroupMap
 * row ids (integers). The other lists are group ids (strings).
 */
export type RoleMember = {
  groups?: any[];
  owner_groups?: any[];
  groups_to_add: string[];
  groups_to_remove: string[];
  owner_groups_to_add: string[];
  owner_groups_to_remove: string[];
  groups_should_expire?: number[];
  owner_groups_should_expire?: number[];
  groups_added_ending_at?: string | null;
  /**
   * @default
   */
  created_reason?: string | null;
};

/**
 * Wire shape for `GET/PUT /api/roles/{id}/members`.
 */
export type RoleMembersSummary = {
  groups_in_role: string[];
  groups_owned_by_role: string[];
};

/**
 * Response for `GET /api/role-requests/{id}` only.
 *
 * Carries the rich `requester_role` / `requested_group` projections —
 * `requester_role.active_user_memberships` and the `requested_group`
 * `active_group_tags` (plus `is_owner` + `app` for app-group requested
 * groups) — that the React role-request detail page renders. List /
 * POST / PUT use `RoleRequestSummary` instead because their eager-load
 * chain is slimmer.
 */
export type RoleRequestDetail = {
  id: string;
  requester_user_id?: string | null;
  requester_role_id?: string | null;
  requested_group_id?: string | null;
  /**
   * @default false
   */
  request_ownership?: boolean;
  /**
   * @default
   */
  request_reason?: string | null;
  request_ending_at?: string | null;
  status: string;
  resolver_user_id?: string | null;
  /**
   * @default
   */
  resolution_reason?: string | null;
  resolved_at?: string | null;
  approval_ending_at?: string | null;
  created_at: string | null;
  updated_at: string | null;
  requester?: OktaUserSummary | null;
  requester_role?: RoleRequestRequesterRoleRef | null;
  active_requester_role?: GroupRef | null;
  requested_group?: RoleRequestRequestedGroupRef | null;
  active_requested_group?: GroupRef | null;
  resolver?: OktaUserSummary | null;
  active_resolver?: OktaUserSummary | null;
};

export type RoleRequestRequestedAppGroupRef = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  deleted_at?: string | null;
  /**
   * @default app_group
   */
  type?: string;
  app_id?: string | null;
  /**
   * @default false
   */
  is_owner?: boolean;
  app?: AppIdRef | null;
  active_group_tags?: OktaGroupTagMapDetail[];
};

export type RoleRequestRequestedGroupRef =
  | (Omit<RoleRequestRequestedOktaGroupRef, 'type'> & {
      type: 'okta_group';
    })
  | (Omit<RoleRequestRequestedAppGroupRef, 'type'> & {
      type: 'app_group';
    });

export type RoleRequestRequestedOktaGroupRef = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  deleted_at?: string | null;
  /**
   * @default okta_group
   */
  type?: string;
  active_group_tags?: OktaGroupTagMapDetail[];
};

export type RoleRequestRequesterRoleRef = {
  id: string;
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default true
   */
  is_managed?: boolean;
  deleted_at?: string | null;
  /**
   * @default role_group
   */
  type?: string;
  active_user_memberships?: OktaUserGroupMemberDetail[];
};

/**
 * Response for `GET /api/role-requests`, `POST /api/role-requests`,
 * and `PUT /api/role-requests/{id}`. Slim shape — no role-member /
 * group-tag eager-load on the embedded refs. The list / POST / PUT
 * pages don't render that data inline.
 */
export type RoleRequestSummary = {
  id: string;
  requester_user_id?: string | null;
  requester_role_id?: string | null;
  requested_group_id?: string | null;
  /**
   * @default false
   */
  request_ownership?: boolean;
  /**
   * @default
   */
  request_reason?: string | null;
  request_ending_at?: string | null;
  status: string;
  resolver_user_id?: string | null;
  /**
   * @default
   */
  resolution_reason?: string | null;
  resolved_at?: string | null;
  approval_ending_at?: string | null;
  created_at: string | null;
  updated_at: string | null;
  requester?: OktaUserSummary | null;
  requester_role?: GroupRef | null;
  active_requester_role?: GroupRef | null;
  requested_group?: GroupRef | null;
  active_requested_group?: GroupRef | null;
  resolver?: OktaUserSummary | null;
  active_resolver?: OktaUserSummary | null;
};

export type SearchAccessRequestQuery = {
  q?: string | null;
  status?: string | null;
  requester_user_id?: string | null;
  assignee_user_id?: string | null;
  requested_group_id?: string | null;
  resolver_user_id?: string | null;
};

export type SearchAppQuery = {
  q?: string | null;
};

export type SearchGroupQuery = {
  q?: string | null;
  managed?: boolean | null;
};

export type SearchGroupRequestQuery = {
  q?: string | null;
  status?: string | null;
  requester_user_id?: string | null;
  assignee_user_id?: string | null;
  requested_group_id?: string | null;
  resolver_user_id?: string | null;
  requested_group_type?: string | null;
  requested_app_id?: string | null;
};

export type SearchGroupRoleAuditQuery = {
  q?: string | null;
  owner?: boolean | null;
  active?: boolean | null;
  needs_review?: boolean | null;
  order_by?: AuditOrderBy;
  /**
   * @default true
   */
  order_desc?: boolean;
  user_id?: string | null;
  group_id?: string | null;
  owner_id?: string | null;
  app_owner?: boolean | null;
  managed?: boolean | null;
  start_date?: number | null;
  end_date?: number | null;
  direct?: boolean | null;
  deleted?: boolean | null;
  role_id?: string | null;
  role_owner_id?: string | null;
};

export type SearchRoleQuery = {
  q?: string | null;
  owner_id?: string | null;
};

export type SearchRoleRequestQuery = {
  q?: string | null;
  status?: string | null;
  requester_user_id?: string | null;
  assignee_user_id?: string | null;
  requested_group_id?: string | null;
  resolver_user_id?: string | null;
  requester_role_id?: string | null;
};

export type SearchTagQuery = {
  q?: string | null;
};

export type SearchUserGroupAuditQuery = {
  q?: string | null;
  owner?: boolean | null;
  active?: boolean | null;
  needs_review?: boolean | null;
  order_by?: AuditOrderBy;
  /**
   * @default true
   */
  order_desc?: boolean;
  user_id?: string | null;
  group_id?: string | null;
  owner_id?: string | null;
  app_owner?: boolean | null;
  managed?: boolean | null;
  start_date?: number | null;
  end_date?: number | null;
  direct?: boolean | null;
  deleted?: boolean | null;
};

export type SearchUserQuery = {
  q?: string | null;
};

export type TagDetail = {
  id: string;
  name: string;
  description?: string | null;
  constraints?: {
    [key: string]: any;
  };
  /**
   * @default true
   */
  enabled?: boolean;
  created_at: string | null;
  updated_at: string | null;
  deleted_at?: string | null;
  active_group_tags?: OktaGroupTagMapDetail[];
  active_app_tags?: AppTagMapDetail[];
};

/**
 * Tag list-endpoint item. Slim field set (id, name, description,
 * enabled, constraints, created_at, updated_at) — does not hydrate
 * `active_group_tags`, which would be an N+1 across the page.
 */
export type TagListItem = {
  id: string;
  name: string;
  description?: string | null;
  constraints?: {
    [key: string]: any;
  };
  /**
   * @default true
   */
  enabled?: boolean;
  created_at: string | null;
  updated_at: string | null;
};

export type TagSummary = {
  id: string;
  name: string;
  constraints?: {
    [key: string]: any;
  };
  /**
   * @default true
   */
  enabled?: boolean;
};

/**
 * Body for PUT /api/apps/{id}. All fields optional (partial update).
 */
export type UpdateAppBody = {
  name?: string | null;
  description?: string | null;
  app_group_lifecycle_plugin?: string | null;
  plugin_data?: {
    [key: string]: any;
  } | null;
  tags_to_add?: string[] | null;
  tags_to_remove?: string[] | null;
};

/**
 * Body for PUT /api/tags/{id}. All fields optional (partial update).
 */
export type UpdateTagBody = {
  name?: string | null;
  description?: string | null;
  constraints?: {
    [key: string]: any;
  } | null;
  enabled?: boolean | null;
};

export type AccessRequestAppGroupRef = {
  id: string;
  /**
   * @default app_group
   */
  type?: string;
  name: string;
  deleted_at?: string | null;
  /**
   * @default false
   */
  is_owner?: boolean;
  app?: AppIdRef | null;
  active_group_tags?: OktaGroupTagMapDetail[];
};

export type AccessRequestOktaGroupRef = {
  id: string;
  /**
   * @default okta_group
   */
  type?: string;
  name: string;
  deleted_at?: string | null;
  active_group_tags?: OktaGroupTagMapDetail[];
};

/**
 * Mirrors `_access_request_ref` at audit.py:184-187.
 */
export type AccessRequestRef = {
  id: string;
};

export type AccessRequestRoleGroupRef = {
  id: string;
  /**
   * @default role_group
   */
  type?: string;
  name: string;
  deleted_at?: string | null;
  active_group_tags?: OktaGroupTagMapDetail[];
  active_role_associated_group_member_mappings?: RoleGroupMapDetail[];
  active_role_associated_group_owner_mappings?: RoleGroupMapDetail[];
};

export type AppGroupCreateBody = {
  /**
   * @maxLength 255
   * @minLength 1
   * @pattern ^[A-Z][A-Za-z0-9-]*$
   */
  name: string;
  description?: string | null;
  tags_to_add?: string[];
  tags_to_remove?: string[];
  type: string;
  app_id?: string | null;
  plugin_data?: {
    [key: string]: any;
  } | null;
};

export type AppGroupRequestBody = {
  /**
   * @maxLength 255
   * @minLength 1
   * @pattern ^[A-Z][A-Za-z0-9-]*$
   */
  requested_group_name: string;
  /**
   * @default
   */
  requested_group_description?: string | null;
  requested_group_tags?: string[];
  requested_ownership_ending_at?: string | null;
  /**
   * @default
   */
  request_reason?: string | null;
  requested_group_type: string;
  requested_app_id: string;
};

export type AppGroupUpdateBody = {
  name?: string | null;
  description?: string | null;
  tags_to_add?: string[];
  tags_to_remove?: string[];
  type: string;
  app_id?: string | null;
  plugin_data?: {
    [key: string]: any;
  } | null;
};

/**
 * Mirrors `_app_ref` at audit.py:120-127.
 */
export type AppRefForAudit = {
  id: string;
  name?: string | null;
  deleted_at?: string | null;
};

export type GroupRefForAudit = {
  [key: string]: any;
};

/**
 * Compact group reference embedded in user/group membership rows.
 */
export type GroupRefForMembership = {
  id: string;
  type: string;
  name: string;
  description?: string | null;
  is_owner?: boolean | null;
  is_managed?: boolean | null;
  deleted_at?: string | null;
  app?: AppIdRef | null;
};

/**
 * Body shape for an entry in `initial_additional_app_groups`.
 */
export type InitialAppGroupBody = {
  name: string;
  /**
   * @default
   */
  description?: string | null;
  /**
   * @default app_group
   */
  type?: string | null;
  plugin_data?: {
    [key: string]: any;
  } | null;
  tags_to_add?: string[] | null;
};

export type OktaGroupCreateBody = {
  /**
   * @maxLength 255
   * @minLength 1
   * @pattern ^[A-Z][A-Za-z0-9-]*$
   */
  name: string;
  description?: string | null;
  tags_to_add?: string[];
  tags_to_remove?: string[];
  type: string;
};

export type OktaGroupRequestBody = {
  /**
   * @maxLength 255
   * @minLength 1
   * @pattern ^[A-Z][A-Za-z0-9-]*$
   */
  requested_group_name: string;
  /**
   * @default
   */
  requested_group_description?: string | null;
  requested_group_tags?: string[];
  requested_ownership_ending_at?: string | null;
  /**
   * @default
   */
  request_reason?: string | null;
  requested_group_type: string;
};

export type OktaGroupUpdateBody = {
  name?: string | null;
  description?: string | null;
  tags_to_add?: string[];
  tags_to_remove?: string[];
  type: string;
};

/**
 * Mirrors `_role_associated_mapping_for_audit` at audit.py:168-181.
 */
export type RoleAssociatedMappingForAudit = {
  id: number;
  is_owner: boolean;
  created_at?: string | null;
  ended_at?: string | null;
  active_group?: GroupRefForAudit | null;
};

export type RoleGroupCreateBody = {
  /**
   * @maxLength 255
   * @minLength 1
   * @pattern ^[A-Z][A-Za-z0-9-]*$
   */
  name: string;
  description?: string | null;
  tags_to_add?: string[];
  tags_to_remove?: string[];
  type: string;
};

/**
 * Mirrors `_role_group_mapping_ref` at audit.py:158-165.
 */
export type RoleGroupMappingForAudit = {
  created_at?: string | null;
  ended_at?: string | null;
  role_group?: RoleGroupRefForAudit | null;
};

export type RoleGroupMappingForMembership = {
  created_at: string | null;
  ended_at?: string | null;
  active_role_group?: RoleGroupMembershipRef | null;
  role_group?: RoleGroupMembershipRef | null;
};

export type RoleGroupMembershipRef = {
  id: string;
  type: string;
  name: string;
  is_managed?: boolean | null;
  deleted_at?: string | null;
};

/**
 * Mirrors `_role_group_ref` at audit.py:146-155.
 */
export type RoleGroupRefForAudit = {
  id: string;
  type: string;
  name: string;
  is_managed?: boolean | null;
  deleted_at?: string | null;
};

export type RoleGroupRequestBody = {
  /**
   * @maxLength 255
   * @minLength 1
   * @pattern ^[A-Z][A-Za-z0-9-]*$
   */
  requested_group_name: string;
  /**
   * @default
   */
  requested_group_description?: string | null;
  requested_group_tags?: string[];
  requested_ownership_ending_at?: string | null;
  /**
   * @default
   */
  request_reason?: string | null;
  requested_group_type: string;
};

export type RoleGroupUpdateBody = {
  name?: string | null;
  description?: string | null;
  tags_to_add?: string[];
  tags_to_remove?: string[];
  type: string;
};

/**
 * Mirrors `_user_summary` at audit.py:106-117. Subset of
 * `OktaUserSummary` from core_schemas.py — no `updated_at`.
 */
export type UserSummaryForAudit = {
  id: string;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  display_name?: string | null;
  deleted_at?: string | null;
  created_at?: string | null;
};
